repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # pre-commit/pre-commit-hooks@4.3.0
    rev: 3298ddab3c13dd77d6ce1fc0baf97691430d84b0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, main]
  - repo: https://github.com/psf/black
    # psf/black@22.12.0
    rev: 2ddea293a88919650266472186620a98a4a8bb37
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    # PyCQA/isort@5.11.5
    rev: 6dfb85379703e7e99834ffc9dc9c05942a202532
    hooks:
      - id: isort

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["--fail-under=8.0"]

  - repo: https://github.com/PyCQA/bandit
    # PyCQA/bandit@1.7.4
    rev: 1ed79063e3672a1c6d91ee27cb648e07a7465344
    hooks:
      - id: bandit
        exclude: src/app/tests/
