name: Deploy Github Runner

on: 
  workflow_dispatch:
    inputs:
      environment: 
        type: choice
        description: Where to deploy
        options: 
        - dev
        - prod
        required: true
        default: dev
        
jobs: 
  deploy:
    name: "Publish in ECR"      
    runs-on: ubuntu-22.04
    environment: ${{ github.event.inputs.environment }}
    permissions:
      id-token: write
      contents: read
    
    continue-on-error: false
    
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838
        with:
          role-to-assume: ${{ vars.IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@261a7de32bda11ba01f4d75c4ed6caf3739e54be

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: github-runner
          IMAGE_TAG: ${{ github.sha }}
        working-directory: src/runner
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT